### PR TITLE
add star history to README.md

### PR DESCRIPTION
**Pull request by Snoup97**

### CODE REVIEW

**Review by shubham-attri — APPROVED** [review]

**Comment by Snoup97** [comment]
@patillacode is this something you want to add?

**Comment by patillacode** [comment]
I think this one for @AntonOsika to decide

I don't have strong feelings

**Comment by Snoup97** [comment]
@AntonOsika opinion?

**Comment by AntonOsika** [comment]
Sure let's add it for now

**Comment by AntonOsika** [comment]
I'd be happy to convinced in how it would help us?

Let's keep the as clean as possible for now

**Comment by AntonOsika** [comment]
feel free to reopen 🚀

**Pull request closed without merging**
