### PR TITLE
add support for anthropic, azure, cohere, replicate.

### PR DESCRIPTION
**Pull request by krrishdholakia**
Hey @AntonOsika, 

Noticed some tickets asking for additional models - https://github.com/AntonOsika/gpt-engineer/issues/516.  I'm working on litellm (simple library to standardize LLM API Calls - https://github.com/BerriAI/litellm) and was wondering if we could be helpful.

Added support for Claude, Cohere, Azure and Llama2 (via Replicate) by adding an additional elif statement in your model file. The code is pretty similar to the OpenAI class - as litellm follows the same pattern as the openai-python sdk.

Would love to know if this helps.

Happy to add additional tests / update documentation, if the initial PR looks good to you.

### CODE REVIEW

**Comment by AntonOsika** [comment]
Thanks @krrishdholakia.

Would be great to have this. I don't see how it adds support for azure thought.

This is what I get when I print `litellm.model_list`:
```
['gpt-4',
 'gpt-4-0613',
 'gpt-4-32k',
 'gpt-4-32k-0613',
 'gpt-3.5-turbo',
 'gpt-3.5-turbo-16k',
 'gpt-3.5-turbo-0613',
 'gpt-3.5-turbo-16k-0613',
 'gpt-3.5-turbo',
 'gpt-3.5-turbo-16k-0613',
 'gpt-3.5-turbo-16k',
 'text-davinci-003',
 'command-nightly',
 'command',
 'command-light',
 'command-medium-beta',
 'command-xlarge-beta',
 'claude-2',
 'claude-instant-1',
 'replicate/']
 ```
 
 I.e. Azure is the same as gpt 

We already use langchain, so might be nice to use their approach to support it.

If you test it with one of those models please let me know.

**Comment by krrishdholakia** [comment]
Hey @AntonOsika, 

Since azure uses the openai sdk and deployment id's are unique, we control it via the azure flag - here's the implementation: https://github.com/BerriAI/litellm/blob/a9186dc40c955680f32a7c02e928a90e0961c92b/litellm/main.py#L60

Okay great - i'll run through some testing with langchain and update this PR

**Comment by AntonOsika** [comment]
Hey @krrishdholakia any news here?

**Comment by krrishdholakia** [comment]
Hi @AntonOsika - missed this - will have this done by EOD

**Comment by krrishdholakia** [comment]
Hey @AntonOsika - we have a Langchain integration live `ChatLiteLLM` and I'm using that. 

Seeing an issue I'm finding hard to repro. Streaming via chatlitellm works fine when i try it on colab 
Screenshot 2023-08-21 at 2 55 19 PM

but breaks in gpt-engineer. Any thoughts on what could be causing this? 
Screenshot 2023-08-21 at 2 56 18 PM

**Comment by krrishdholakia** [comment]
For context here's our langchain integration - https://python.langchain.com/docs/integrations/chat/litellm

**Comment by krrishdholakia** [comment]
Acknowledging this + your PR - let's get this fixed asap.

**Comment by AntonOsika** [comment]
I don't know the issue.

Let's do this for now:

We stash this PR, get it back in when we want LiteLLM.

Until then, do you wanna check if it's possible to use azure according to the docs? (i.e. setting base_url)

https://gpt-engineer.readthedocs.io/en/latest/open_models.html

**Comment by krrishdholakia** [comment]
Hey @AntonOsika, 
It is possible to override the api base. 

You can do it either on the module - `litellm.api_base = ".."` or dynamically in the completion call - `completion(.., custom_api_base="..."`

We also work with Azure directly: 
Screenshot 2023-09-02 at 2 54 11 PM

**Pull request closed without merging**
