### PR TITLE
Allow model string to be changed (Fixes #328)

### LINKED ISSUE #328: [Suggestion] Add compatibility with gpt3.5-turbo
This would likely be as simple as adding a setting/switch to select the model:

https://github.com/AntonOsika/gpt-engineer/blob/abb9f2332de033a0e40adc0f3492a73df9cfc1cc/scripts/rerun_edited_message_logs.py#L16
https://github.com/AntonOsika/gpt-engineer/blob/abb9f2332de033a0e40adc0f3492a73df9cfc1cc/gpt_engineer/main.py#L21
https://github.com/AntonOsika/gpt-engineer/blob/abb9f2332de033a0e40adc0f3492a73df9cfc1cc/gpt_engineer/ai.py#L11

It looks like this would just be adding an argument here:
https://github.com/AntonOsika/gpt-engineer/blob/abb9f2332de033a0e40adc0f3492a73df9cfc1cc/gpt_engineer/main.py#L18-L34

### PR DESCRIPTION
**Pull request by Explosion-Scratch**

### CODE REVIEW

**Comment by carlthome** [comment]
Shouldn't the default be something else than "model"?

**Comment by Explosion-Scratch** [comment]
> Shouldn't the default be something else than "model"?

I didn't know that was the default value 💀

**Comment by Explosion-Scratch** [comment]
Thought it was the description lmao

**Comment by carlthome** [comment]
LGTM! Triggering tests.

**Comment by nickolay-kondratyev** [comment]
Any plans to merge soon?

**Comment by carlthome** [comment]
Thanks for bump @nickolay-kondratyev and thanks for the contribution @Explosion-Scratch!

**Comment by Explosion-Scratch** [comment]
No problem! 😄

**Pull request merged**
