### PR TITLE
Allow .env file variables to be used

### PR DESCRIPTION
**Pull request by ScorchChamp**
This fix allows the .env to be used for environment variables. 
(Especially useful for windows devices)

### CODE REVIEW

**Comment by navyfighter12** [comment]
This works for me on windows 11. Thank you
Hopefully gets accepted

**Comment by boktoday** [comment]
Yes please.

**Comment by LeeStevens318** [comment]
Can this be re-opened? Hasn't been merged to main?

**Comment by patillacode** [comment]
I am really open to this although I believe @AntonOsika is not convinced.

There have been other attempts at this, for example #29 

I personally like the fact of having a `.env` file to be used as a "settings" file in a way, especially for secrets.

Can we revisit this @AntonOsika ?

**Comment by patillacode** [comment]
Open discussion about this in #135

**Comment by jebarpg** [comment]
+1
I would 3rd this addition as well. @AntonOsika

**Comment by YaJannik** [comment]
+1
This chance is necessary in my opinion. Having this problem too.

**Comment by patillacode** [comment]
Please go to the discussion and add you +1 there #135

**Pull request closed without merging**
