### PR TITLE
Bug Fix: Model Name Should Not Be Verified Through OpenAI with Custom Endpoint

### LINKED ISSUE #331: adding a custom api end point
I use a custom and free api endpoint so I would like to add a feature  which is similar to:

```
export OPENAI_API_KEY=[your api key]
```

so I would like to have:

```
export OPENAI_API_BASE=[your custom api base url]
```

If you don't export it then it will have the default base url.

is it appropriate for me to work on this or if it is already implemented then please let me know.

### PR DESCRIPTION
**Pull request by JinchuLi2002**
Closes #331

## Overview
This Pull Request aims to fix the bug that prevents setting custom API endpoint.

## Background
Many open-source LLMs (e.g. FastChat, ChatGLM) provides OpenAI-compatible APIs, which means once these models are set up and running locally, users should be able to query them, still via ```openai.ChatCompletion.create()```,  simply by setting ```export OPENAI_API_BASE=<where model is running>```. However the current version of GPT-Engineer attempts to verify model name through OpenAI even if a custom api base is set.

## Changes 
* Modified such that model name is only verified (by ```fallback_model()```) only if a custom ```OPENAI_API_BASE``` is not set.

### CODE REVIEW

**Comment by AntonOsika** [comment]
Thanks @JinchuLi2002 !

The only problem with this is that the collect_learnings will not use the right model name if we move the fallback here.

To address, could for example use `ai.model`.

Question though: How do you propose we get the right model name when setting other OPENAI_API_BASE than the default? 

Would love to merge this if we can solve this!

**Comment by JinchuLi2002** [comment]
@AntonOsika 
Hi Anton, thanks for the reply! :D

1. For your first point, could you be more specific how the issue could rise? The only impact with me moving ```fallback_model()``` with regards to ```collect_learnings()``` is that it could allow a non-OpenAI model name to be passed to the latter, if a custom end point is set. Do you mean that ```send_learning()``` would mandate the model name sent to be a OpenAI model?
2. Sadly, I don't think there's an effective way of verifying the model name with a custom endpoint. Because it differs with the local models which the user deploys. For example, the model name is 'codegen' for [FauxPilot](https://github.com/fauxpilot/fauxpilot/blob/main/documentation/client.md) and 'vicuna-7b-v1.3' for [Fastchat](https://github.com/lm-sys/FastChat/blob/main/docs/openai_api.md)

**Comment by AntonOsika** [comment]
Should we maybe do whatever langchain does to standardize model selection?

**Comment by JinchuLi2002** [comment]
@AntonOsika For LangChain I don't think they have a standardized model selection mechanism either. For openai models, it's defaulted to 'text-davinci-003' ([source](https://github.com/hwchase17/langchain/blob/master/langchain/llms/openai.py#L135)), and for google_palm model, it's straight up ```model_name: str = "models/text-bison-001"``` ([source](https://github.com/hwchase17/langchain/blob/master/langchain/llms/google_palm.py#L82)) and it's for the users to make sure the model_name is set correctly.

**Comment by AntonOsika** [comment]
Hey there are a few things that would be needed to merge this:

1. Consider using OpenaiChat as a field of the AI class: https://github.com/hwchase17/langchain/blob/1f4a51cb9c84c6a061cda729c4cdd3783d98922c/langchain/llms/openai.py#L659
2. Pass in the base into AI, not get it from env variable


I think there is another PR that looks at this

**Comment by JinchuLi2002** [comment]
thanks @AntonOsika !
will open a separate PR after I do more research

**Pull request closed without merging**
