### PR TITLE
Add pull request and issue templates

### PR DESCRIPTION
**Pull request by aroramrinaal**
### Description:
This pull request adds pull request (PR) and issue templates to improve the contribution process and communication within the project. The PR template provides a structure for clear submissions, while the issue template helps in creating well-structured reports. These templates ensure consistency, improve communication, and streamline the process.

### I have created the following templates:

Pull Request Template: [Link to the PR template file](https://github.com/aroramrinaal/gpt-engineer/blob/add-pr-issue-templates/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md)
Issue Template: [Link to the issue template file](https://github.com/aroramrinaal/gpt-engineer/blob/add-pr-issue-templates/.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md)

Fixes: #84

### CODE REVIEW

**Comment by patillacode** [comment]
I think this will enhance the experience of going through issues, thanks @aroramrinaal 

Since this is a change that affects how the project is presented to the users/contributors I'll wait for someone else to merge, but I have approved it.

Maybe @AntonOsika wants to re-word something or get rid a check or two.

cc @carlthome @FOLLGAD

**Comment by carlthome** [comment]
Personally hesitant to introduce heavy templates, and prefer a polished CI over requiring manual steps by humans.

Would be funny if this repo started not only self-hosting with `gpt-engineer` but also if it auto-reviewed PRs with LLMs as well.

**Comment by patillacode** [comment]
We maybe don't need templates or at least not as heavy but I definitely think we would benefit from an issues template even if minimal.

I am down for CI steps but there are no CI steps that can help the user properly explain an issue!

**Comment by AntonOsika** [comment]
Great initiative.

And yes: we should definitely set up LLM reviews! Any ideas on which ones @carlthome?

Also I agree that it's a good idea to see if we can make it faster to fill in the templates by simplifying. Or even say that you can adapt the template to your liking.

What do you think @aroramrinaal, anything you think is not "crucial" to include?

**Comment by patillacode** [comment]
Hey @AntonOsika 

Templates don't seem to be properly applied, I don't have access to the settings of the repo, so it needs to be you.
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Pull request merged**
