### PR TITLE
Multiline Inputs

### PR DESCRIPTION
**Pull request by GreicodexJM**
Added multi line inputs to provide clarification and modified prompts to included folder structure of the output files

### CODE REVIEW

**Comment by FOLLGAD** [comment]
Probably not the right way to approach this since it increases the complexity of the UI. Thoughts @patillacode ?

**Comment by patillacode** [comment]
A few points:

- I am not sure what problem this is solving.
- I agree with @FOLLGAD, not gonna say counter intuitive but not intuitive.
- Regarding prompts, I am OK with the small changes.
- FYI pre-commit check is not passing, please make sure to follow the [CONTRIBUTING ](https://github.com/AntonOsika/gpt-engineer/blob/main/.github/CONTRIBUTING.md)guidelines and make sure you are running the pre-commit hooks on your branch.

**Comment by GreicodexJM** [comment]
The motivation for this change was that during the clarification phase I would get from ChatGPT multiple questions like:
```
Areas that need clarification:
1. What specific functionalities do the Model, View, and Controller components of the snake game have?
2. How are the MVC components split into separate files?
3. What are the specific keyboard controls for the snake game?
4. Are there any specific requirements or constraints for writing the snake game in Python?
```

**Comment by GreicodexJM** [comment]
I'm open to suggestions to use another condition to indicate that the multi line input has been completed. But I do think that for anything more complex than example programs, user feedback will contain more than single sentence answers. i.e. Output examples, Input definitions, data schemas, etc.

**Comment by GreicodexJM** [comment]
I'll redo this following the CONTRIBUTION guide

**Pull request closed without merging**
