### PR TITLE
Made a GUI Version (NOT TESTED)

### PR DESCRIPTION
**Pull request by LopeKinz**
Gui is more User Friendly. So i decided to make a GUI Version of main.py 
Merge into BETA or create a new Branch for GUI

### CODE REVIEW

**Comment by shakesBeardZ** [comment]
@LopeKinz can you share what's in your GUI, a video or GIF will be good idea

**Comment by LopeKinz** [comment]
> @LopeKinz can you share what's in your GUI, a video or GIF will be good idea

Give me some time. ill change some things

**Comment by LopeKinz** [comment]
https://imgur.com/a/abOuBJM

Alpha Preview. 
First Textbox is Prompt
Second Textbox is Log Output

Second Pic shows The filepicker (linux) also works on windows

**Comment by AntonOsika** [comment]
Great to see PoCs like this!

I'd recommend adding gpt-engineer as a dependency and make it work will separately before submitting a PR though, currently not as a part of the roadmap

**Comment by LopeKinz** [comment]
> Great to see PoCs like this!
> 
> I'd recommend adding gpt-engineer as a dependency and make it work will separately before submitting a PR though, currently not as a part of the roadmap

okay ill get to work on the gui version

**Comment by mach7** [comment]
> > Great to see PoCs like this!
> > I'd recommend adding gpt-engineer as a dependency and make it work will separately before submitting a PR though, currently not as a part of the roadmap
> 
> okay ill get to work on the gui version

Do you have a repo you're working on that we can follow to watch the progress of this?

**Comment by suhidamadaud** [comment]
ไม่มีอะไรให้ดู

**Comment by LopeKinz** [comment]
> > > Great to see PoCs like this!
> 
> > > I'd recommend adding gpt-engineer as a dependency and make it work will separately before submitting a PR though, currently not as a part of the roadmap
> 
> > 
> 
> > okay ill get to work on the gui version
> 
> 
> 
> Do you have a repo you're working on that we can follow to watch the progress of this?

My Fork of this repo. I don’t have time rn to work on it but it will be soon finished

**Comment by jenspacito** [comment]
Yrs good idea, we train with data every day

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
