### PR TITLE
file_selector path as input path

### PR DESCRIPTION
**Pull request by lukaspetersson**
To select files for improvement faster, the inital path of the file selector should be the input path.

This is especially important if using the CLI option as the printed tree can become very large otherwise.

### CODE REVIEW

**Comment by ATheorell** [comment]
Cannot judge whether there are any unforseen drawbacks of this. Input @pbharrin @UmerHA ?

**Comment by UmerHA** [comment]
> Cannot judge whether there are any unforseen drawbacks of this. Input @pbharrin @UmerHA ?

Hey, I don't see any drawback. Both changed functions (`gui_file_selector` and `terminal_file_selector`) still return a list of filenames, so it should be fine.

**Comment by AntonOsika** [comment]
I like this.

Makes me think we should refactor the core logic and CLI UX specific things to make it easier to take decisions on what makes sense from UX perspective, and how the core building blocks should work.

**Comment by AntonOsika** [comment]
See #718, tagging @lukaspetersson for visibility

**Pull request merged**
