### PR TITLE
Add gpt model model parameter

### PR DESCRIPTION
**Pull request by KiranPranay**
By defualt, the model would be gpt-4.
But, the user can specify, the model they want.

### CODE REVIEW

**Comment by abhishekASB** [comment]
wew

**Comment by ilutoo** [comment]
not sure about this, model gpt-4 can not work on proff lvl

**Comment by ilutoo** [comment]
sometimes is work ye, but its mistacke of galagramos inside the knek

**Comment by ScorchChamp** [comment]
It already works if you run main.py --model gpt-3.5-turbo (so this PR is useless)

**Pull request closed without merging**
