### PR TITLE
Improved chat parsing with no AI logic

### PR DESCRIPTION
**Pull request by goncalomoita**
This fixes compatibility issues in PR [#87](https://github.com/AntonOsika/gpt-engineer/pull/87) that have arisen from recent changes to the repository.
Additionally, an improvement to the parser unit tests has been done.

The goal of the this parser is to make sense of what the LLM has provided without requiring another inference call which adds time and cost overhead. My remarks on this matter were stated in [#35](https://github.com/AntonOsika/gpt-engineer/issues/35#issuecomment-1594508297).
Further debate has been conducted in PR [#94](https://github.com/AntonOsika/gpt-engineer/pull/94)

### CODE REVIEW

**Review by bmeddeb — APPROVED** [review]

**Comment by patillacode** [comment]
Hi @goncalomoita 

thanks a lot for this PR.

I would like to merge this but I need confirmation/feedback from @AntonOsika and anyone else who wants to chime in.

I am thinking that we can merge this and remove it later if [#94](https://github.com/AntonOsika/gpt-engineer/pull/94#issuecomment-1595779838) gets done. I think #94 fixes this with functions though

**Comment by AntonOsika** [comment]
- Solves a clear problem ✅
- Problem is significant ✅
- Solution is robust ✅

Looks good to me!

**Comment by AntonOsika** [comment]
The only thing is that I always want simpler solutions ❌

Less code -> easier to change the repository later.

What we could do:

Use a system prompt as a final message that explicitly asks for the format we prefer.

**Comment by EnzoMartin** [comment]
I had a variety of issues with chat parsing, I made similar improvements including supporting directory creation in #140

**Comment by patillacode** [comment]
@AntonOsika 

Merging now since you agree, we can always simplify if possible later.

Just to be clear I think #94 is the way to go, it is simpler imo and uses the model itself via functions to solve this issue.

Until that is merged (if ever) this provides a solution for an issue that many users have at the moment.

**Comment by patillacode** [comment]
Thank you @goncalomoita

**Pull request merged**
