### PR TITLE
Added CODE_OF_CONDUCT.md to the .github directory

### PR DESCRIPTION
**Pull request by jebarpg**
Moved the CODE_OF_CONDUCT.md out of the main directory and into the correct .github directory

### CODE REVIEW

**Review by w3bdesign — APPROVED** [review]

**Comment by patillacode** [comment]
Hi @jebarpg 

I think something is off here... 🤔 

Are you sure your fork is up to date with the `main` branch in the original repo?

**Comment by jebarpg** [comment]
> Hi @jebarpg
> 
> I think something is off here... 🤔
> 
> Are you sure your fork is up to date with the `main` branch in the original repo?

@patillacode 
I cloned the main repo and my fork repo and then added all the files from the main repo into my fork repo and then finally moved the CODE_OF_CONDUCT.md to the .github directory. Then I deleted the previous PR and created this one with the CODE_OF_CONDUCT.md inside the correct directory. 



Second commit/push:
I also made another commit/push to my fork with changes for the model fall back issue, which will make both the main.py and the rerun_edited_message_logs.py model fall back to the same gpt-3.5-turbo model. I created a parent script model_select.py inside the main directory of the repo and it centralizes the logic that was originally added in ai.py and makes it accessable to both main.py and rerun_edited_message_logs.py. Also so in the future when we want to choose a different fall back it only has to be changed in one spot and not in two scripts. 

I don't know how to create multiple pull requests for different commit/pushes to my repo. But I created this pull request right after the first commit for the CODE_OF_CONDUCT.md, and then later committed/pushed the model fallback to my fork. could use some help understanding how to do this correctly.

**Comment by patillacode** [comment]
As a first step, I would suggest adding one change per PR.
Not adding several things in one PR makes reviews easier.
If the matter is a localized issue we can understand it better and merge right away.

For example, adding the `.github/CODE_OF_CONDUCT.md` file could be in just one PR, let's start with that one since it is simple.

step by step:

- make sure your `main` branch (in your fork) is up to date/identical to the original repo's `main` branch.
```bash
$ git pull origin main
# or hit the "Sync" button in your fork
```

- create a branch `add-code-of-conduct` 
```
$ git checkout -b add-code-of-conduct
```

- add the file, commit and push
```
$ git add .github/CODE_OF_CONDUCT.md
```

- create a PR from your new branch `add-code-of-conduct` to this repo's `main` branch.
You can do this through the webUI in github

You can follow the same steps for each change you want to make, with different branches of course. 

is that helpful?

**Comment by jebarpg** [comment]
@patillacode this is perfect! thank you! I'll bookmark this for reference. Yea I did want to keep the two separated since they solve different issues. I just didn't know that branching was how to do it. Thanks for improving me 💯

**Comment by patillacode** [comment]
@jebarpg 
I am closing this in favor of you creating one PR for each thing you want to change like we discussed.

**Comment by jebarpg** [comment]
> @jebarpg I am closing this in favor of you creating one PR for each thing you want to change like we discussed.

done. PRs are up

**Pull request closed without merging**
