### PR TITLE
Fixes for #1

### PR DESCRIPTION
**Pull request by Jeadie**
Was hoping to add some functionality to gpt-engineer, but wanted #1  merged beforehand. 

These should up to date with main. We should squash and merge due to number of commits.

### CODE REVIEW

**Comment by offiub** [comment]
okay your issues

**Comment by AntonOsika** [comment]
Hey @Jeadie appreciate the PR a lot!

Would be happy to have you keep contributing – we're looking for passionate maintainers of GPT Engineer.

I have 2 comments in my review – would you be able to address?

The

**Comment by AntonOsika** [comment]
@patillacode suggested we use pip-tools and I see [why](https://news.ycombinator.com/item?id=34287447)
image

However, I don't know what either poetry or pip-tools would do for us right now.

Unless I get good arguments I'd say we just keep it simple with pip for now?

I'd be happy to move the code though if you can address not moving to poetry etc @Jeadie

**Comment by AntonOsika** [comment]
Note:

Would need to update readme.md if we don't go with poetry

**Comment by patillacode** [comment]
Sure, I kept it simple for now.
Let's revisit the matter if necessary when the time comes.

**Comment by patillacode** [comment]
Hi @Jeadie 

Please find below a summary of the changes you did and my comments about them:

- `.gitignore` 
too big for my taste, we are not generating over half of those patterns, plus other PRs have been merged with a few additions in the file, we should add as necessary and avoid the copy/paste boilerplate, WDYT?

- `poetry`
accommodating the project for `poetry`, things like `main.py` becoming `__main__.py` or moving all python files into a subfolder called `gpt_engineer` 

As mentioned by @AntonOsika we are gonna wait when it comes to handling dependencies, for now we are going the good-old route of using `requirements.txt` as is.
JFYI even if we did handle dependencies otherwise, we are leaning towards `pip-tools` more than `poetry`

- _formatting_
I see you must have your editor configured to run some sort of auto formatting (maybe `black`?)
that has also been added and it will be enforced by [pre-commit hooks](https://github.com/AntonOsika/gpt-engineer/issues/57) soon

Most of the things you seem to have addressed in this PR have been addressed in others already (`.gitignore` & formatting) and the other thing (`poetry`) we are not implementing for now.


Please let me know if I misunderstood something or if you have any feedback.

Closing in favour of house-keeping but please do comment!

**Comment by JacobFV** [comment]
Thanks! I'm excited to see whatever direction gpt-engineer goes.

**Comment by Jeadie** [comment]
I'm happy with pip (it's generally my default too, tbh). I mainly just wanted the improved structure from #1 . 

Looking forward to contributing

**Pull request closed without merging**
